const NavigationData: any = [
  {
    title: "Reporting",
    url: "/reporting",
    id: "menu-reporting",
    icon: "icofont-slightly-smile",
    hasAlert: true,
    children: [
      {
        title: "Sales Dashboard",
        url: "/reporting/sales_dashboard",
        id: "menu-sales-dashboard",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Forecast",
        url: "/reporting/forecast",
        id: "menu-forecast",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Consumer Insights",
        url: "/reporting/consumer_insights",
        id: "menu-consumer-insights",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Supplier Registration Compliance",
        url: "/reporting/supplier_registration_compliance",
        id: "menu-supplier-registration-compliance",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Fulfillment Performance Diagnostics",
        url: "/reporting/supplier_dashboard",
        id: "menu-fulfillment-performance-diagnostics",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Lead Time Performance",
        url: "/reporting/lead_time_performance",
        id: "menu-leadtime-performance",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Customer Incidents Dashboard",
        url: "/reporting/customer_incidents_dashboard",
        id: "menu-customer-incidents-dashboard",
        icon: null,
        hasAlert: false,
        children: [],
      },
    ],
  },
  {
    title: "Tickets",
    url: "/tickets",
    id: "tickets",
    icon: "icofont-ui-note",
    hasAlert: false,
    children: [],
  },
  {
    title: "Orders",
    url: "/orders",
    id: "menu-orders-management",
    icon: "icofont-truck-loaded",
    hasAlert: false,
    children: [
      {
        title: "Order Management Overview",
        url: "/orders/overview",
        id: "menu-orders-management-overview",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Item Management",
        url: "/orders/item-management",
        id: "menu-orders-management-item",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "All Order Alerts",
        url: "null",
        id: "menu-orders-all-order-alerts",
        icon: null,
        hasAlert: false,
        children: [
          {
            title: "Menu Order",
            url: "/orders/menu-order",
            id: "menu-orders-all-order-alerts-overview",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Overdue Orders",
            url: "/orders/overdue",
            id: "menu-orders-overdue-orders",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Late Registration",
            url: "",
            id: "menu-orders-late-registration",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Pending Cancellations",
            url: "",
            id: "menu-orders-pending-cancellations",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Pending Ship Address Changes",
            url: "",
            id: "menu-orders-allalerts-pending-shipaddress-changes",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Pending Ship Speed Changes",
            url: "",
            id: "menu-orders-pending-shipspeed-changes",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Unconfirmed Replacement Parts",
            url: "",
            id: "menu-orders-allalerts-unconfirmed-replacement-parts",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Late Replacement Parts",
            url: "",
            id: "menu-orders-late-replacement-parts",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Pending RMAs",
            url: "",
            id: "menu-orders-pending-rm-as",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Failed Pickups",
            url: "",
            id: "menu-orders-failed-pickups",
            icon: null,
            hasAlert: false,
            children: [],
          },
        ],
      },
      {
        title: "Order Exports",
        url: "",
        id: "menu-orders-exports",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Pickup Center",
        url: "",
        id: "menu-orders-pickup-center",
        icon: null,
        hasAlert: false,
        children: [],
      },
    ],
  },
  {
    title: "CastleGate",
    url: null,
    id: "menu-wfs-management",
    icon: "icofont-building",
    hasAlert: false,
    children: [
      {
        title: "Get Started",
        url: "",
        id: "menu-wfs-management-get-started",
        icon: null,
        hasAlert: false,
        children: [],
      },
    ],
  },
  {
    title: "Inventory",
    url: null,
    id: "menu-inventory",
    icon: "icofont-industries-4",
    hasAlert: false,
    children: [
      {
        title: "Inventory Overview",
        url: "",
        id: "menu-inventory-overview",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Inventory Integration Score",
        url: "",
        id: "menu-inventory-integration-score",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Inventory Alerts",
        url: "",
        id: "menu-inventory-alerts",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Inventory Management",
        url: "",
        id: "menu-inventory-management",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Product Discontinuation",
        url: "",
        id: "menu-inventory-product-discontinuation",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Current Inventory",
        url: "",
        id: "menu-inventory-current-inventory",
        icon: null,
        hasAlert: false,
        children: [],
      },
    ],
  },
  // {
  //   title: "Products",
  //   url: null,
  //   id: "menu-pricing",
  //   icon: "list-alt",
  //   hasAlert: true,
  //   children: [
  //     {
  //       title: "Pricing Overview",
  //       url: "/v/catalog/catalog_management/index",
  //       id: "menu-pricing-overview",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //     {
  //       title: "Product Management",
  //       url: "/v/catalog/catalog_management/index",
  //       id: "menu-pricing-product-management",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //     {
  //       title: "Pricing Hub",
  //       url: null,
  //       id: "menu-pricing-hub",
  //       icon: null,
  //       hasAlert: true,
  //       children: [
  //         {
  //           title: "",
  //           url: "/v/supplier/pricing_hub/app/index",
  //           id: "menu-pricing-hub-overview",
  //           icon: null,
  //           hasAlert: false,
  //           children: [],
  //         },
  //         {
  //           title: "Pricing Updates",
  //           url: "/v/supplier/pricing/app/index",
  //           id: "menu-pricing-hub-updates",
  //           icon: null,
  //           hasAlert: true,
  //           children: [],
  //         },
  //         {
  //           title: "Pricing Request Management",
  //           url: "/v/supplier/pricing_request_management/batch_summary/index",
  //           id: "menu-pricing-hub-request-management",
  //           icon: null,
  //           hasAlert: false,
  //           children: [],
  //         },
  //       ],
  //     },
  //     {
  //       title: "Shipping Dimensions",
  //       url: "/v/catalog/shipping_dimension/shipping_dimension/search",
  //       id: "menu-pricing-shipping-dimensions",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //     {
  //       title: "Product Attribute Management",
  //       url: "/v/catalog/product_specification/management/index",
  //       id: "menu-pricing-product-attribute-management",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //     {
  //       title: "Tried & True",
  //       url: "/triedandtrue",
  //       id: "menu-pricing-tried-and-true",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //     {
  //       title: "Supplier-funded Reviews",
  //       url: "/fundedreviews",
  //       id: "menu-pricing-funded-reviews",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //     {
  //       title: "Product Compliance",
  //       url: "/v/catalog/product_certification/product_certification/index",
  //       id: "menu-pricing-product-compliance",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //     {
  //       title: "Shop Your Catalog",
  //       url: "/v/catalog/shop_your_catalog/index",
  //       id: "menu-shop-your-catalog",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //     {
  //       title: "Image & Media Management",
  //       url: "/v/product_media/media_management/load",
  //       id: "menu-pricing-media-management",
  //       icon: null,
  //       hasAlert: false,
  //       children: [],
  //     },
  //   ],
  // },
  {
    title: "Premium Shelf",
    url: null,
    id: "menu-events-premium-shelf",
    icon: "icofont-dining-table",
    hasAlert: false,
    children: [
      {
        title: "Accelerant Hub",
        url: "",
        id: "menu-events-accelerant-hub",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Promotions Manager",
        url: "",
        id: "menu-events-promotions-manager",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Events",
        url: null,
        id: "menu-events",
        icon: null,
        hasAlert: false,
        children: [
          {
            title: "Event Planning",
            url: "",
            id: "menu-events-planning",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Event Preview",
            url: "",
            id: "menu-events-preview",
            icon: null,
            hasAlert: false,
            children: [],
          },
        ],
      },
    ],
  },
  {
    title: "Account Management",
    url: null,
    id: "menu-account",
    icon: "icofont-ui-user-group",
    hasAlert: true,
    children: [
      {
        title: "Warehouse Management",
        url: null,
        id: "menu-account-warehouse-management",
        icon: null,
        hasAlert: false,
        children: [
          {
            title: "Overview",
            url: "",
            id: "menu-account-warehouse-management-overview",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Warehouse Closures",
            url: "",
            id: "menu-account-warehouse-closures",
            icon: null,
            hasAlert: false,
            children: [],
          },
          {
            title: "Warehouse Hours",
            url: "",
            id: "menu-account-warehouse-normal-hours",
            icon: null,
            hasAlert: false,
            children: [],
          },
        ],
      },
      {
        title: "Supplier Account Details",
        url: "",
        id: "menu-account-supplier-account-details",
        icon: null,
        hasAlert: true,
        children: [],
      },
      {
        title: "Supplier Setup Details",
        url: "",
        id: "menu-account-supplier-setup-details",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Certificate of Insurance Management & Control",
        url: "",
        id: "menu-account-coi-management",
        icon: null,
        hasAlert: true,
        children: [],
      },
    ],
  },
  {
    title: "Download Center",
    url: "/v/supplier/download_center/management/app",
    id: "download-center",
    icon: "icofont-download",
    hasAlert: false,
    children: [],
  },
  {
    title: "Help & Support",
    url: null,
    id: "help-and-support",
    icon: "icofont-live-support",
    hasAlert: false,
    children: [
      {
        title: "Help Center",
        url: "/help/2",
        id: "help-center",
        icon: null,
        hasAlert: false,
        children: [],
      },
      {
        title: "Contact Us",
        url: "/v/supplier/contact/wayfair_contact/index",
        id: "contact-us",
        icon: null,
        hasAlert: false,
        children: [],
      },
    ],
  },
];

export { NavigationData };
